/* ============================================================
   StallUp — Mock Data
   ============================================================ */

const DATA = {
  // Demo user accounts
  users: [
    { id: 'u1', name: 'Riya Sharma', email: 'vendor@stallup.in', password: 'demo123', role: 'vendor', city: 'Indore', initials: 'RS', joined: 'March 2024' },
    { id: 'u2', name: 'Arjun Mehta', email: 'funder@stallup.in', password: 'demo123', role: 'funder', city: 'Mumbai', initials: 'AM', joined: 'January 2024' },
    { id: 'u3', name: 'Priya Kapoor', email: 'admin@stallup.in', password: 'demo123', role: 'admin', city: 'New Delhi', initials: 'PK', joined: 'December 2023' },
  ],

  // Business proposals
  proposals: [
    {
      id: 'p1',
      businessName: 'Momo Junction',
      category: 'Momos & Dumplings',
      categoryEmoji: '🥟',
      vendor: 'Riya Sharma',
      vendorId: 'u1',
      city: 'Indore',
      neighborhood: 'Vijay Nagar',
      experience: 4,
      capitalRequired: 80000,
      fundingPurpose: 'Upgrade to a professional-grade steamer, purchase a new cart with branding, bulk raw material stocking, and local social media promotion.',
      useOfFunds: [
        { item: 'New cart with canopy & branding', amount: 25000 },
        { item: 'Professional steamer (3-tier)', amount: 18000 },
        { item: 'Initial raw material stock', amount: 20000 },
        { item: 'Local marketing & signage', amount: 12000 },
        { item: 'Working capital buffer', amount: 5000 },
      ],
      dailyCustomers: 80,
      avgOrderValue: 120,
      monthlyRevenue: 288000,
      monthlyExpenses: {
        rawMaterial: 86400,
        rent: 4000,
        staff: 8000,
        utilities: 3000,
        marketing: 2000,
        misc: 4600
      },
      monthlyProfit: 35000,
      breakEvenMonths: 2.5,
      status: 'active',
      verificationStatus: 'verified',
      trustScore: 87,
      interests: 4,
      description: "I've been running a momo stall in Vijay Nagar for 4 years now. Started with a small folding table; today we serve 80+ customers daily. My special Kurkure Momo and Afghani Momo have a loyal fanbase among college students and office-goers. I want to upgrade my setup to serve faster, maintain hygiene standards, and build a small brand. This funding will let me do that without draining my savings.",
      photos: ['🥟', '🫕', '🍱'],
      verifiedItems: ['Aadhar Card', 'GST Registration', 'Food Safety Certificate (FSSAI)', 'Bank Account Proof'],
      pendingItems: ['Business Address Proof'],
      mapPosition: { x: 45, y: 38 },
      dateSubmitted: '2024-11-15',
      stage: 'Expansion',
    },
    {
      id: 'p2',
      businessName: 'Chhappan Chaat Corner',
      category: 'Chaat & Street Snacks',
      categoryEmoji: '🍢',
      vendor: 'Suresh Patel',
      vendorId: 'u4',
      city: 'Indore',
      neighborhood: 'Chhappan Dukaan',
      experience: 7,
      capitalRequired: 60000,
      fundingPurpose: 'New cooking equipment, additional seating, and refrigeration unit for ingredients.',
      useOfFunds: [
        { item: 'Commercial refrigerator', amount: 22000 },
        { item: 'Additional cooking equipment', amount: 18000 },
        { item: 'Seating & furniture', amount: 12000 },
        { item: 'Raw material stock', amount: 8000 },
      ],
      dailyCustomers: 120,
      avgOrderValue: 90,
      monthlyRevenue: 324000,
      monthlyExpenses: {
        rawMaterial: 97200,
        rent: 8000,
        staff: 12000,
        utilities: 4000,
        marketing: 1500,
        misc: 5300
      },
      monthlyProfit: 48500,
      breakEvenMonths: 1.5,
      status: 'active',
      verificationStatus: 'verified',
      trustScore: 92,
      interests: 7,
      description: "Running chaat since 2017 near the famous Chhappan Dukaan area. Known for our Dahi Puri and Sev Puri. We have consistent daily footfall from both locals and tourists visiting this landmark. Looking to upgrade infrastructure to serve more customers during peak hours.",
      photos: ['🍢', '🥗', '🧆'],
      verifiedItems: ['Aadhar Card', 'GST Registration', 'FSSAI License', 'Bank Account Proof', 'Business Address Proof'],
      pendingItems: [],
      mapPosition: { x: 55, y: 52 },
      dateSubmitted: '2024-10-28',
      stage: 'Established',
    },
    {
      id: 'p3',
      businessName: 'Idli Ammas Kitchen',
      category: 'South Indian',
      categoryEmoji: '🫔',
      vendor: 'Lakshmi Venkat',
      vendorId: 'u5',
      city: 'Indore',
      neighborhood: 'MG Road',
      experience: 3,
      capitalRequired: 45000,
      fundingPurpose: 'Commercial wet grinder, new utensils, and packaging for takeaway orders.',
      useOfFunds: [
        { item: 'Commercial wet grinder', amount: 18000 },
        { item: 'Takeaway packaging setup', amount: 10000 },
        { item: 'Cooking equipment', amount: 12000 },
        { item: 'Working capital', amount: 5000 },
      ],
      dailyCustomers: 60,
      avgOrderValue: 100,
      monthlyRevenue: 180000,
      monthlyExpenses: {
        rawMaterial: 54000,
        rent: 5000,
        staff: 6000,
        utilities: 2500,
        marketing: 1000,
        misc: 2500
      },
      monthlyProfit: 22000,
      breakEvenMonths: 2.0,
      status: 'active',
      verificationStatus: 'verified',
      trustScore: 79,
      interests: 2,
      description: "Serving authentic South Indian breakfast since 2021 in the MG Road area. My idlis are soft, sambar is freshly made, and I source ingredients from trusted suppliers. Most of my customers are morning regulars who trust my food quality. Looking to add takeaway capability to grow without needing a physical expansion.",
      photos: ['🫔', '🍛', '🥘'],
      verifiedItems: ['Aadhar Card', 'FSSAI License', 'Bank Account Proof'],
      pendingItems: ['GST Registration', 'Business Address Proof'],
      mapPosition: { x: 38, y: 60 },
      dateSubmitted: '2024-11-05',
      stage: 'Growing',
    },
    {
      id: 'p4',
      businessName: 'Sharma Ji Ka Poha',
      category: 'Breakfast Specials',
      categoryEmoji: '🍽️',
      vendor: 'Ramesh Sharma',
      vendorId: 'u6',
      city: 'Indore',
      neighborhood: 'Rajwada',
      experience: 12,
      capitalRequired: 35000,
      fundingPurpose: 'Modernize setup, buy stainless steel cookware, and create a small seating area.',
      useOfFunds: [
        { item: 'Stainless steel equipment set', amount: 15000 },
        { item: 'Seating & shed', amount: 12000 },
        { item: 'Display & signage', amount: 8000 },
      ],
      dailyCustomers: 150,
      avgOrderValue: 60,
      monthlyRevenue: 270000,
      monthlyExpenses: {
        rawMaterial: 81000,
        rent: 3000,
        staff: 5000,
        utilities: 2000,
        marketing: 500,
        misc: 2500
      },
      monthlyProfit: 55000,
      breakEvenMonths: 0.7,
      status: 'active',
      verificationStatus: 'verified',
      trustScore: 95,
      interests: 11,
      description: "Sharma Ji Ka Poha is a 12-year-old institution in Rajwada. We are open only from 7am to 11am, yet we serve 150+ bowls of poha and jalebi every day. Multiple food bloggers and travel guides have featured us. This is not a startup — it is a legacy being modernized.",
      photos: ['🍽️', '🫕', '☕'],
      verifiedItems: ['Aadhar Card', 'GST Registration', 'FSSAI License', 'Bank Account Proof', 'Business Address Proof'],
      pendingItems: [],
      mapPosition: { x: 48, y: 45 },
      dateSubmitted: '2024-10-10',
      stage: 'Established',
    },
    {
      id: 'p5',
      businessName: 'Punjabi Dhaba Express',
      category: 'North Indian / Dhaba',
      categoryEmoji: '🍛',
      vendor: 'Gurpreet Singh',
      vendorId: 'u7',
      city: 'Indore',
      neighborhood: 'Palasia',
      experience: 2,
      capitalRequired: 120000,
      fundingPurpose: 'Tandoor installation, commercial gas pipeline, and initial inventory for full menu launch.',
      useOfFunds: [
        { item: 'Tandoor oven & installation', amount: 45000 },
        { item: 'Commercial gas setup', amount: 25000 },
        { item: 'Kitchen equipment & utensils', amount: 30000 },
        { item: 'Initial inventory & spices', amount: 20000 },
      ],
      dailyCustomers: 45,
      avgOrderValue: 180,
      monthlyRevenue: 243000,
      monthlyExpenses: {
        rawMaterial: 97200,
        rent: 12000,
        staff: 18000,
        utilities: 5000,
        marketing: 3000,
        misc: 4800
      },
      monthlyProfit: 30000,
      breakEvenMonths: 4.0,
      status: 'active',
      verificationStatus: 'pending',
      trustScore: 65,
      interests: 1,
      description: "Started a dhaba-style counter in 2022. The food is authentic Punjabi — dal makhani, butter naan, kadhai paneer. We have built a small but devoted customer base. To serve properly, we need a tandoor. Right now we are buying tandoori items from outside and it's eating into margins.",
      photos: ['🍛', '🫓', '🥘'],
      verifiedItems: ['Aadhar Card', 'Bank Account Proof'],
      pendingItems: ['GST Registration', 'FSSAI License', 'Business Address Proof'],
      mapPosition: { x: 62, y: 35 },
      dateSubmitted: '2024-11-20',
      stage: 'Early Stage',
    },
    {
      id: 'p6',
      businessName: 'The Juice Bar Co.',
      category: 'Beverages & Juices',
      categoryEmoji: '🧃',
      vendor: 'Meera Joshi',
      vendorId: 'u8',
      city: 'Indore',
      neighborhood: 'Scheme 54',
      experience: 5,
      capitalRequired: 55000,
      fundingPurpose: 'Commercial cold-press juicer, fruit storage refrigerator, and new counter setup.',
      useOfFunds: [
        { item: 'Cold-press juicer', amount: 28000 },
        { item: 'Commercial refrigerator', amount: 18000 },
        { item: 'Counter & display setup', amount: 9000 },
      ],
      dailyCustomers: 70,
      avgOrderValue: 80,
      monthlyRevenue: 168000,
      monthlyExpenses: {
        rawMaterial: 67200,
        rent: 6000,
        staff: 8000,
        utilities: 3000,
        marketing: 2000,
        misc: 1800
      },
      monthlyProfit: 28000,
      breakEvenMonths: 2.0,
      status: 'active',
      verificationStatus: 'verified',
      trustScore: 83,
      interests: 3,
      description: "Running a fresh juice bar in Scheme 54 since 2019. Healthy beverages using seasonal fruits, no artificial additives. Popular with the gym-going crowd and office workers. Looking to upgrade to cold-press to expand the product range and attract health-conscious consumers.",
      photos: ['🧃', '🍊', '🥤'],
      verifiedItems: ['Aadhar Card', 'GST Registration', 'FSSAI License', 'Bank Account Proof'],
      pendingItems: ['Business Address Proof'],
      mapPosition: { x: 70, y: 55 },
      dateSubmitted: '2024-11-01',
      stage: 'Expansion',
    },
  ],

  // Vendor's own proposal (for vendor dashboard)
  vendorProposal: {
    exists: true,
    proposalId: 'p1',
  },

  // Admin verification queue
  verificationQueue: [
    {
      id: 'v1',
      vendorName: 'Gurpreet Singh',
      businessName: 'Punjabi Dhaba Express',
      city: 'Indore',
      submittedDate: '2024-11-20',
      proposalId: 'p5',
      documents: [
        { name: 'Aadhar Card', status: 'uploaded' },
        { name: 'Bank Account Proof', status: 'uploaded' },
        { name: 'GST Registration', status: 'missing' },
        { name: 'FSSAI License', status: 'missing' },
        { name: 'Business Address Proof', status: 'missing' },
      ],
    },
    {
      id: 'v2',
      vendorName: 'Sunita Devi',
      businessName: 'Sunita Bhajji Stall',
      city: 'Ujjain',
      submittedDate: '2024-11-18',
      proposalId: null,
      documents: [
        { name: 'Aadhar Card', status: 'uploaded' },
        { name: 'Bank Account Proof', status: 'uploaded' },
        { name: 'GST Registration', status: 'uploaded' },
        { name: 'FSSAI License', status: 'uploaded' },
        { name: 'Business Address Proof', status: 'uploaded' },
      ],
    },
    {
      id: 'v3',
      vendorName: 'Rahul Verma',
      businessName: 'RV Rolls & Wraps',
      city: 'Bhopal',
      submittedDate: '2024-11-22',
      proposalId: null,
      documents: [
        { name: 'Aadhar Card', status: 'uploaded' },
        { name: 'Bank Account Proof', status: 'uploaded' },
        { name: 'GST Registration', status: 'uploaded' },
        { name: 'FSSAI License', status: 'pending_review' },
        { name: 'Business Address Proof', status: 'uploaded' },
      ],
    },
  ],

  // Platform metrics
  platformMetrics: {
    totalVendors: 148,
    verifiedVendors: 112,
    pendingVerifications: 3,
    activeProposals: 89,
    totalInterestsExpressed: 342,
    flaggedReports: 2,
    citiesCovered: 14,
    capitalRequested: 8640000,
  },

  // Testimonials
  testimonials: [
    {
      quote: "StallUp helped me find serious supporters who actually understood my business. No middlemen, no gimmicks. Within 3 weeks of listing, I had 4 people express genuine interest.",
      name: 'Riya Sharma',
      role: 'Momo Junction, Indore',
      emoji: '👩‍🍳',
    },
    {
      quote: "I wanted to support local food entrepreneurs but had no idea where to start. StallUp showed me verified profiles with real financials. That transparency was the deciding factor.",
      name: 'Arjun Mehta',
      role: 'Supporter, Mumbai',
      emoji: '💼',
    },
    {
      quote: "The verification process was thorough but fair. It gave my profile the credibility it deserved after 12 years of running my business. First listing got 11 interests in a month.",
      name: 'Ramesh Sharma',
      role: 'Sharma Ji Ka Poha, Indore',
      emoji: '👨‍🍳',
    },
  ],

  // Funder preferences (mock)
  funderPreferences: {
    budget: { min: 50000, max: 100000 },
    categories: ['Momos & Dumplings', 'Chaat & Street Snacks', 'Breakfast Specials'],
    cities: ['Indore'],
  },
};
